/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utils;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class StringUtilsTest {
    @Test
    void is12PositiveNumber() {
        assertTrue(StringUtils.isPositiveNumber("12"));
    }
}
